In [8]:
import sys, os, itertools, sklearn
sys.path.append('/home/roquero/CausalAggregation/Code')
import pandas as pd
import numpy as np
import _pickle as pkl
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import linear_model
from sklearn.linear_model import LassoCV, Lasso
from sklearn import datasets
from sklearn.metrics import auc
from scipy.interpolate import UnivariateSpline
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%reload_ext autoreload
%autoreload 2
from backfitting import Backfitting
from boosting import Boosting
from base_environment import BaseEnvironment
from collection_environment import CollectionEnvironment
from regression_method import PolynomialRegression
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures


/home/roquero/miniconda3/lib/python3.7/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))


In [9]:
structural_eq_y = (lambda input_samples:input_samples[0] + 5*input_samples[1] * input_samples[2] -5*input_samples[2] * input_samples[3] + input_samples[4])
fh = {'input_keys':[], 'structural_eq': (lambda input_samples:input_samples)} #eps1: eps1)}
f1 = {'input_keys':['h'], 'structural_eq': (lambda input_samples:input_samples[0] * input_samples[1])} #eps1: eps1)}
f2 = {'input_keys':['h', 'x1'], 'structural_eq': (lambda input_samples: 3*input_samples[0]+input_samples[1]-input_samples[2])} #[x1, eps2]: 3*x1 + eps2)}
f3 = {'input_keys':['h', 'x1'], 'structural_eq': (lambda input_samples: - input_samples[0] + 2*input_samples[1] + input_samples[2])}
fy = {'input_keys':['h','x1','x2','x3'], 'structural_eq': structural_eq_y}


In [13]:
sh = lambda n_samples: np.random.normal(size=n_samples)
s1 = lambda n_samples: np.random.normal(size=n_samples)
s2 = lambda n_samples: np.random.normal(size=n_samples)
s3 = lambda n_samples: np.random.normal(size=n_samples)
sy = lambda n_samples: np.random.normal(size=n_samples)

In [14]:
topo_order = ['h','x1','x2','x3','y']
y_key = 'y'
x_key = ['x1','x2','x3']

In [15]:
structural_equation_dict = {'x1':f1, 'x2':f2, 'x3':f3, 'y':fy, 'h':fh}
disturbance_sampler_dict = {'x1':s1, 'x2':s2, 'x3':s3, 'y':sy, 'h':sh}

In [16]:
base = BaseEnvironment(structural_equation_dict, disturbance_sampler_dict, topo_order, y_key, x_key)

In [30]:
coll_env = CollectionEnvironment(base)

coll_env.add_environment('e1', {'x1':{'type':'independent'}}, 100000)#, 'x2':{'type':'independent'}}, 1000)
coll_env.add_environment('e2', {'x1':{'type':'independent'},'x2':{'type':'independent'}}, 100000)
coll_env.add_environment('e3', {'x2':{'type':'independent'},'x3':{'type':'independent'}}, 100000)



{'x1': {'type': 'independent'}}
{'x1': {'type': 'independent'}, 'x2': {'type': 'independent'}}
{'x2': {'type': 'independent'}, 'x3': {'type': 'independent'}}


In [31]:
backfit = Backfitting(PolynomialRegression, max_n_iter=100, params_method ={'power_features':2, 'include_bias':False})

backfit.fit(coll_env)

1
2
e1
['x0', 'x0^2']
[ 0.18326651 -5.01622625]
[0.14083056 4.84443196]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[-0.16186783  0.01353157  5.03879274 -4.98611575 -0.02619468]
[-0.06682798  0.02216706 -4.85276395  4.92305683 -0.06060764]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[-2.83108122e-02 -3.59644024e-02  6.29809651e-02 -4.96211237e+00
  2.68616371e-03]
[-2.10051108e-02  4.84586849e-06  6.35581522e-02 -5.00407722e+00
  9.18885047e-04]
3
e1
['x0', 'x0^2']
[0.14083056 4.84443196]
[0.06463587 4.92572074]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[-0.06682798  0.02216706 -4.85276395  4.92305683 -0.06060764]
[-0.06263952  0.01456178 -4.92711098  5.0069859  -0.06088389]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[-2.10051108e-02  4.84586849e-06  6.35581522e-02 -5.00407722e+00
  9.18885047e-04]
[-1.33834959e-02  5.22611728e-04  6.32692787e-02 -5.00461681e+00
  8.15073763e-04]
4
e1
['x0', 'x0^2']
[0.06463587 4.92572074]
[0.06030083 4.91797807]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[-0.062

e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 1.08533918e-01  5.32349123e-04  5.84213432e-02 -5.00462084e+00
  8.15029569e-04]
[ 1.16153760e-01  5.32349123e-04  5.81183390e-02 -5.00462084e+00
  8.15029569e-04]
21
e1
['x0', 'x0^2']
[0.00780885 4.77031042]
[4.52931680e-03 4.76108068e+00]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[-0.00686918 -0.11498188 -4.77128574  5.00807276 -0.05574245]
[-3.58965098e-03 -1.22601718e-01 -4.76205600e+00  5.00807276e+00
 -5.54394469e-02]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 1.16153760e-01  5.32349123e-04  5.81183390e-02 -5.00462084e+00
  8.15029569e-04]
[ 1.23773602e-01  5.32349123e-04  5.78153348e-02 -5.00462084e+00
  8.15029569e-04]
22
e1
['x0', 'x0^2']
[4.52931680e-03 4.76108068e+00]
[1.24978852e-03 4.75185094e+00]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[-3.58965098e-03 -1.22601718e-01 -4.76205600e+00  5.00807276e+00
 -5.54394469e-02]
[-3.10122704e-04 -1.30221561e-01 -4.75282626e+00  5.00807276e+00
 -5.51364428e-02]
e3
['x0', 'x1', 'x0^2', 'x0 x1'

e1
['x0', 'x0^2']
[-0.05122266  4.60417511]
[-0.05450219  4.59494537]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.05216233 -0.25213904 -4.60515043  5.00807276 -0.05028838]
[ 0.05544186 -0.25975888 -4.59592069  5.00807276 -0.04998537]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 2.53310923e-01  5.32349123e-04  5.26642636e-02 -5.00462084e+00
  8.15029569e-04]
[ 2.60930765e-01  5.32349123e-04  5.23612594e-02 -5.00462084e+00
  8.15029569e-04]
40
e1
['x0', 'x0^2']
[-0.05450219  4.59494537]
[-0.05778172  4.58571563]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.05544186 -0.25975888 -4.59592069  5.00807276 -0.04998537]
[ 0.05872139 -0.26737872 -4.58669096  5.00807276 -0.04968237]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 2.60930765e-01  5.32349123e-04  5.23612594e-02 -5.00462084e+00
  8.15029569e-04]
[ 2.68550607e-01  5.32349123e-04  5.20582552e-02 -5.00462084e+00
  8.15029569e-04]
41
e1
['x0', 'x0^2']
[-0.05778172  4.58571563]
[-0.06106125  4.5764859 ]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']

e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 3.90468085e-01  5.32349123e-04  4.72101882e-02 -5.00462084e+00
  8.15029569e-04]
[ 3.98087928e-01  5.32349123e-04  4.69071840e-02 -5.00462084e+00
  8.15029569e-04]
58
e1
['x0', 'x0^2']
[-0.1135337   4.42881007]
[-0.11681323  4.41958033]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.11447337 -0.39691604 -4.42978539  5.00807276 -0.0445313 ]
[ 0.1177529  -0.40453589 -4.42055565  5.00807276 -0.04422829]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 3.98087928e-01  5.32349123e-04  4.69071840e-02 -5.00462084e+00
  8.15029569e-04]
[ 4.05707770e-01  5.32349123e-04  4.66041798e-02 -5.00462084e+00
  8.15029569e-04]
59
e1
['x0', 'x0^2']
[-0.11681323  4.41958033]
[-0.12009276  4.41035059]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.1177529  -0.40453589 -4.42055565  5.00807276 -0.04422829]
[ 0.12103242 -0.41215573 -4.41132591  5.00807276 -0.04392529]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 4.05707770e-01  5.32349123e-04  4.66041798e-02 -5.00462084e+00
  8.

76
e1
['x0', 'x0^2']
[-0.17256521  4.26267476]
[-0.17584474  4.25344502]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.17350488 -0.53407321 -4.26365008  5.00807276 -0.03907722]
[ 0.1767844  -0.54169305 -4.25442034  5.00807276 -0.03877422]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 5.35245090e-01  5.32349123e-04  4.14531086e-02 -5.00462084e+00
  8.15029569e-04]
[ 5.42864933e-01  5.32349123e-04  4.11501044e-02 -5.00462084e+00
  8.15029569e-04]
77
e1
['x0', 'x0^2']
[-0.17584474  4.25344502]
[-0.17912427  4.24421528]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.1767844  -0.54169305 -4.25442034  5.00807276 -0.03877422]
[ 0.18006393 -0.54931289 -4.2451906   5.00807276 -0.03847121]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 5.42864933e-01  5.32349123e-04  4.11501044e-02 -5.00462084e+00
  8.15029569e-04]
[ 5.50484775e-01  5.32349123e-04  4.08471002e-02 -5.00462084e+00
  8.15029569e-04]
78
e1
['x0', 'x0^2']
[-0.17912427  4.24421528]
[-0.1824038   4.23498554]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^

e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 6.72402253e-01  5.32349123e-04  3.59990331e-02 -5.00462084e+00
  8.15029569e-04]
[ 6.80022095e-01  5.32349123e-04  3.56960290e-02 -5.00462084e+00
  8.15029569e-04]
95
e1
['x0', 'x0^2']
[-0.23487625  4.08730971]
[-0.23815578  4.07807997]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.23581591 -0.67885021 -4.08828503  5.00807276 -0.03332014]
[ 0.23909544 -0.68647005 -4.07905529  5.00807276 -0.03301714]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 6.80022095e-01  5.32349123e-04  3.56960290e-02 -5.00462084e+00
  8.15029569e-04]
[ 6.87641938e-01  5.32349123e-04  3.53930248e-02 -5.00462084e+00
  8.15029569e-04]
96
e1
['x0', 'x0^2']
[-0.23815578  4.07807997]
[-0.2414353   4.06885023]
e2
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 0.23909544 -0.68647005 -4.07905529  5.00807276 -0.03301714]
[ 0.24237497 -0.6940899  -4.06982556  5.00807276 -0.03271413]
e3
['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[ 6.87641938e-01  5.32349123e-04  3.53930248e-02 -5.00462084e+00
  8.

In [32]:
samples = np.random.normal(size=(3,10))

In [33]:
backfit.true_function_y(samples)
backfit.output_function_merged(samples)

array([ 0.04165879, -0.3058572 , 19.86957893,  3.77279475,  0.56778692,
       -1.29935063, 13.08932627, -0.78696129, -4.03075389, -1.12018225])

array([ 0.04416182, -0.30408675, 19.90598733,  3.77987031,  0.57087478,
       -1.2941324 , 13.11191967, -0.7887333 , -4.03113895, -1.10836989])

In [34]:
backfit.evaluate_gap()

0.00013218486497338844

In [35]:
backfit.output_model_variation

{'e1': [261.78042816551635,
  0.017968795181804546,
  0.001634447101149726,
  0.0017438300349267703,
  0.001744464022381687,
  0.0017444879289251949,
  0.0017444878328015132,
  0.0017444878408240485,
  0.0017444878407050003,
  0.0017444878407106357,
  0.0017444878407089299,
  0.0017444878407078916,
  0.0017444878407086256,
  0.0017444878407081857,
  0.0017444878407084751,
  0.0017444878407096036,
  0.001744487840709331,
  0.0017444878407073352,
  0.0017444878407084433,
  0.001744487840708806,
  0.001744487840708784,
  0.0017444878407084138,
  0.0017444878407082442,
  0.001744487840709201,
  0.0017444878407093145,
  0.0017444878407096031,
  0.0017444878407088108,
  0.001744487840708787,
  0.0017444878407093442,
  0.0017444878407090315,
  0.0017444878407090693,
  0.0017444878407083019,
  0.0017444878407078764,
  0.0017444878407098985,
  0.0017444878407089275,
  0.001744487840709053,
  0.0017444878407097137,
  0.0017444878407087572,
  0.001744487840710382,
  0.0017444878407099909,
  0.001