In [13]:
import sys, os, itertools, sklearn
sys.path.append('/home/roquero/CausalAggregation/Code')
import pandas as pd
import numpy as np
import _pickle as pkl
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import linear_model
from sklearn.linear_model import LassoCV, Lasso
from sklearn import datasets
from sklearn.metrics import auc
from scipy.interpolate import UnivariateSpline
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%reload_ext autoreload
%autoreload 2
from backfitting import Backfitting
from base_environment import BaseEnvironment
from collection_environment import CollectionEnvironment
from regression_method import PolynomialRegression
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures


In [26]:
structural_eq_y = (lambda input_samples:input_samples[0] + 5*input_samples[1] * input_samples[2] + input_samples[3])
fh = {'input_keys':[], 'structural_eq': (lambda input_samples:input_samples)} #eps1: eps1)}
f1 = {'input_keys':['h'], 'structural_eq': (lambda input_samples:input_samples[0] * input_samples[1])} #eps1: eps1)}
f2 = {'input_keys':['h', 'x1'], 'structural_eq': (lambda input_samples: 3*input_samples[0]+input_samples[1]-input_samples[2])} #[x1, eps2]: 3*x1 + eps2)}
fy = {'input_keys':['h','x1','x2'], 'structural_eq': structural_eq_y}


In [27]:
sh = lambda n_samples: np.random.normal(size=n_samples)
s1 = lambda n_samples: np.random.normal(size=n_samples)
s2 = lambda n_samples: np.random.normal(size=n_samples)
sy = lambda n_samples: np.random.normal(size=n_samples)

In [28]:
topo_order = ['h','x1','x2','y']
y_key = 'y'
x_key = ['x1','x2']

In [29]:
structural_equation_dict = {'x1':f1, 'x2':f2, 'y':fy, 'h':fh}
disturbance_sampler_dict = {'x1':s1, 'x2':s2, 'y':sy, 'h':sh}

In [30]:
base = BaseEnvironment(structural_equation_dict, disturbance_sampler_dict, topo_order, y_key, x_key)

In [31]:
coll_env = CollectionEnvironment(base)

coll_env.add_environment('e1', {'x1':{'type':'independent'}}, 100000)#, 'x2':{'type':'independent'}}, 1000)
coll_env.add_environment('e2', {'x1':{'type':'independent'},'x2':{'type':'independent'}}, 100000)


{'x1': {'type': 'independent'}}
{'x1': {'type': 'independent'}, 'x2': {'type': 'independent'}}


In [32]:
backfit = Backfitting(PolynomialRegression, max_n_iter=100, params_method ={'power_features':2, 'include_bias':False})

backfit.fit(coll_env)

1
2
[0.14382063 5.06854386]
[0.15651217 5.07996711]
[-1.46155721e-01 -4.60983947e-03 -5.07157677e+00  4.99695906e+00
 -2.13288995e-04]
[-1.58847263e-01 -4.60983947e-03 -5.08300003e+00  4.99695906e+00
 -2.13288995e-04]
3
[0.15651217 5.07996711]
[0.16920371 5.09139036]
[-1.58847263e-01 -4.60983947e-03 -5.08300003e+00  4.99695906e+00
 -2.13288995e-04]
[-1.71538805e-01 -4.60983947e-03 -5.09442328e+00  4.99695906e+00
 -2.13288995e-04]
4
[0.16920371 5.09139036]
[0.18189525 5.10281362]
[-1.71538805e-01 -4.60983947e-03 -5.09442328e+00  4.99695906e+00
 -2.13288995e-04]
[-1.84230348e-01 -4.60983947e-03 -5.10584653e+00  4.99695906e+00
 -2.13288995e-04]
5
[0.18189525 5.10281362]
[0.1945868  5.11423687]
[-1.84230348e-01 -4.60983947e-03 -5.10584653e+00  4.99695906e+00
 -2.13288995e-04]
[-1.96921890e-01 -4.60983947e-03 -5.11726978e+00  4.99695906e+00
 -2.13288995e-04]
6
[0.1945868  5.11423687]
[0.20727834 5.12566012]
[-1.96921890e-01 -4.60983947e-03 -5.11726978e+00  4.99695906e+00
 -2.13288995e-04]
[

[-6.28434332e-01 -4.60983947e-03 -5.50566032e+00  4.99695906e+00
 -2.13288995e-04]
[-6.41125874e-01 -4.60983947e-03 -5.51708357e+00  4.99695906e+00
 -2.13288995e-04]
41
[0.63879078 5.51405066]
[0.65148232 5.52547391]
[-6.41125874e-01 -4.60983947e-03 -5.51708357e+00  4.99695906e+00
 -2.13288995e-04]
[-6.53817416e-01 -4.60983947e-03 -5.52850682e+00  4.99695906e+00
 -2.13288995e-04]
42
[0.65148232 5.52547391]
[0.66417387 5.53689716]
[-6.53817416e-01 -4.60983947e-03 -5.52850682e+00  4.99695906e+00
 -2.13288995e-04]
[-6.66508959e-01 -4.60983947e-03 -5.53993007e+00  4.99695906e+00
 -2.13288995e-04]
43
[0.66417387 5.53689716]
[0.67686541 5.54832041]
[-6.66508959e-01 -4.60983947e-03 -5.53993007e+00  4.99695906e+00
 -2.13288995e-04]
[-6.79200501e-01 -4.60983947e-03 -5.55135333e+00  4.99695906e+00
 -2.13288995e-04]
44
[0.67686541 5.54832041]
[0.68955695 5.55974367]
[-6.79200501e-01 -4.60983947e-03 -5.55135333e+00  4.99695906e+00
 -2.13288995e-04]
[-6.91892044e-01 -4.60983947e-03 -5.56277658e+00 

[1.10837785 5.93671096]
[1.12106939 5.94813421]
[-1.11071294e+00 -4.60983947e-03 -5.93974387e+00  4.99695906e+00
 -2.13288995e-04]
[-1.12340449e+00 -4.60983947e-03 -5.95116712e+00  4.99695906e+00
 -2.13288995e-04]
79
[1.12106939 5.94813421]
[1.13376093 5.95955746]
[-1.12340449e+00 -4.60983947e-03 -5.95116712e+00  4.99695906e+00
 -2.13288995e-04]
[-1.13609603e+00 -4.60983947e-03 -5.96259037e+00  4.99695906e+00
 -2.13288995e-04]
80
[1.13376093 5.95955746]
[1.14645248 5.97098071]
[-1.13609603e+00 -4.60983947e-03 -5.96259037e+00  4.99695906e+00
 -2.13288995e-04]
[-1.14878757e+00 -4.60983947e-03 -5.97401362e+00  4.99695906e+00
 -2.13288995e-04]
81
[1.14645248 5.97098071]
[1.15914402 5.98240396]
[-1.14878757e+00 -4.60983947e-03 -5.97401362e+00  4.99695906e+00
 -2.13288995e-04]
[-1.16147911e+00 -4.60983947e-03 -5.98543687e+00  4.99695906e+00
 -2.13288995e-04]
82
[1.15914402 5.98240396]
[1.17183556 5.99382721]
[-1.16147911e+00 -4.60983947e-03 -5.98543687e+00  4.99695906e+00
 -2.13288995e-04]
[

In [33]:
samples = np.random.normal(size=(2,10))

In [34]:
backfit.true_function_y(samples)
backfit.output_function_merged(samples)

array([-0.02721545,  6.5435046 ,  5.77865999, -1.68212044, -7.90187672,
        0.33600075, -3.89770914,  0.66114873,  5.35703266, -2.66225056])

array([-0.02271855,  6.55378134,  5.77032872, -1.67313195, -7.90532311,
        0.34929425, -3.8908253 ,  0.6741829 ,  5.36513006, -2.65591061])

In [35]:
backfit.evaluate_gap()

9.626789274893624e-05

In [12]:
backfit.output_model_variation

{'e1': [66.44267198242483, 0.0006988026213696315],
 'e2': [96.10134284431204, 0.0006988026213695825]}

In [41]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
lr = LinearRegression()
lr.fit(X, y)
lr.coef_


LinearRegression()

array([1., 2.])

In [38]:

poly.n_output_features_

4

In [39]:
X

array([[0, 1],
       [2, 3],
       [4, 5]])