In [204]:
import numpy as np
import scipy as sp
import pandas as pd
from sklearn.linear_model import LinearRegression
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%reload_ext autoreload
%autoreload 2
import itertools
import sys
sys.path.append('/home/roquero/CausalAggregation/Code')
from generateEnvironment import GenerateEnvironment
from solveProblem import SolveProblem
import matplotlib as mpl
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica"]})
np.set_printoptions(suppress=True)
np.set_printoptions(precision=5)

In [214]:
n_dim=20
connectivity_e0 = np.zeros((n_dim,n_dim))
connectivity_e0[np.arange(1,n_dim), np.arange(0,n_dim-1)] = np.random.normal(size=n_dim-1)
connectivity_e0[1:,0]=5
y_index=12
x_indices=np.hstack([np.arange(1,y_index),(np.arange(y_index+1,n_dim))])
print('x_dim: {}'.format(len(x_indices)))
n_samples=50000
n_reps=100
coord=1

x_dim: 18


In [215]:
list_dict_interventions = [{i:{'type':'independent'} for i in np.array([3,17])}]

solver = SolveProblem(connectivity_e0,x_indices,y_index)

list_environments = [solver.generate_intervention(n_samples, dict_interventions)
                     for dict_interventions in list_dict_interventions]


problem = solver.solve_problem(0.05, list_environments, n_samples)


In [216]:
m, z, p = solver.combine_constraints(list_environments)
m.shape
z.shape
p.shape

(18, 2)

(2,)

(18, 18)

In [217]:
problem.variables()[0].value 

array([ 0.     ,  0.01075,  0.     ,  0.     ,  0.00629, -0.02787,
        0.     ,  0.     ,  0.     ,  0.19062, -0.92573,  0.13154,
        0.     ,  0.     ,  0.     ,  0.     ,  0.03239,  0.01859])

In [219]:
solver.beta
solver.estimator_LR(solver.generate_intervention(50000, {}))
solver.estimator_Lasso(solver.generate_intervention(50000, list_dict_interventions[0]))

array([ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
        0.     ,  0.     ,  0.     ,  0.     , -1.09747,  0.     ,
        0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ])

array([ 0.02905,  0.0174 ,  0.01735,  0.00966,  0.10737,  0.04702,
        0.06438,  0.03616,  0.01917,  0.06134, -1.02414,  0.17595,
       -0.0126 , -0.02319, -0.00536, -0.003  ,  0.02502,  0.0408 ])

array([ 0.     ,  0.01279, -0.     ,  0.     ,  0.04596, -0.     ,
        0.     ,  0.     ,  0.     ,  0.16502, -0.87947,  0.09088,
        0.     ,  0.     ,  0.08378, -0.     ,  0.     ,  0.02977])

In [104]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)

NameError: name 'coverage' is not defined

In [ ]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)

In [ ]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)

In [ ]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)