In [2]:
import numpy as np
import scipy as sp
import pandas as pd
from sklearn.linear_model import LinearRegression
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%reload_ext autoreload
%autoreload 2
import itertools
import sys
sys.path.append('/home/roquero/CausalAggregation/Code')
from generateEnvironment import GenerateEnvironment
from solveProblem import SolveProblem
import matplotlib as mpl
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica"]})
np.set_printoptions(suppress=True)
np.set_printoptions(precision=5)

In [188]:
n_dim=20
connectivity_e0 = np.zeros((n_dim,n_dim))
connectivity_e0[np.arange(1,n_dim), np.arange(0,n_dim-1)] = np.random.normal(size=n_dim-1)
connectivity_e0[1:,0]=2
y_index=12
x_indices=np.hstack([np.arange(1,y_index),(np.arange(y_index+1,n_dim))])
print('x_dim: {}'.format(len(x_indices)))
n_samples=50000
n_reps=100
coord=1

x_dim: 18


In [196]:
list_dict_interventions = [{i:{'type':'independent'} for i in np.array([11,13])}]

solver = SolveProblem(connectivity_e0,x_indices,y_index)

list_environments = [solver.generate_intervention(n_samples, dict_interventions)
                     for dict_interventions in list_dict_interventions]


problem = solver.solve_problem(0.05, list_environments, n_samples)


In [197]:
m, z, p = solver.combine_constraints(list_environments)
m.shape
z.shape
p.shape

(18, 2)

(2,)

(18, 18)

In [198]:
problem.variables()[0].value 

array([ 0.08596,  0.05507,  0.05298,  0.06558,  0.03009,  0.     ,
       -0.03813,  0.     ,  0.0697 , -0.     ,  0.     , -0.06218,
       -0.     , -0.     ,  0.     ,  0.04765,  0.0668 ,  0.16158])

In [192]:
solver.beta
solver.estimator_LR(solver.generate_intervention(500, {}))
solver.estimator_Lasso(solver.generate_intervention(50000, list_dict_interventions[0]))

array([0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.01394, 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     ])

array([ 0.06833,  0.11384,  0.04728,  0.07813,  0.06124,  0.17033,
        0.03303, -0.01333,  0.26079,  0.02897,  0.09095, -0.34823,
        0.11624, -0.05007, -0.06343,  0.07606,  0.13196,  0.10533])

array([ 0.09874,  0.07772,  0.07282,  0.10292,  0.07882,  0.1352 ,
       -0.     ,  0.     ,  0.11285,  0.01498,  0.     , -0.06285,
       -0.     , -0.     , -0.     ,  0.04062,  0.07203,  0.07086])

In [104]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)

NameError: name 'coverage' is not defined

In [ ]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)

In [ ]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)

In [ ]:
np.mean(coverage)
np.std(coverage)
np.mean(lenght)
np.std(lenght)