In [1]:
import numpy as np
import scipy as sp
import pandas as pd
from sklearn.linear_model import LinearRegression
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%reload_ext autoreload
%autoreload 2
import itertools
import sys
sys.path.append('/home/roquero/CausalAggregation/Code')
from generateEnvironment import GenerateEnvironment
from solveProblem import SolveProblem
import matplotlib as mpl
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica"]})
np.set_printoptions(suppress=True)
np.set_printoptions(precision=4)

/home/roquero/miniconda3/lib/python3.7/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))


In [2]:
n_dim=9
connectivity_e0 = np.array([
    [0]*9,
    [2,0,0,0,2,1,0,0,0],
    [0,0,0,0,0,-1,0,0,0],
    [-1,0,0,0,0,2,-1,0,0],
    [0,0,0,0,0,0,0,1,0],
    [0]*9,
    [0,0,0,0,0,0,0,3,0],
    [0]*9,
    [3,2,1,-1,0,0,0,0,0],
]
)
y_index=8
x_indices=np.arange(1,y_index)
print('x_dim: {}'.format(len(x_indices)))
n_samples=100000

x_dim: 7


In [3]:
for n_samples in np.array([100,500,1000,10000,100000,500000,1000000]):
    print('\nSimulation for sample size = {}'.format(n_samples))
    list_dict_interventions = [{i:{'type':'independent'} for i in np.array([1])},
                               {i:{'type':'independent'} for i in np.array([3])}]
    solver = SolveProblem(connectivity_e0,x_indices,y_index)
    list_environments = [solver.generate_intervention(n_samples, dict_interventions)
                         for dict_interventions in list_dict_interventions]
    
    print('True beta: \n{}'.format(solver.beta))
    print('Least squares estimate of beta: \n{}'.format(solver.estimator_LR(solver.generate_intervention(n_samples, {}))))
    print('Lasso CV estimate of beta: \n{}'.format(solver.estimator_Lasso(solver.generate_intervention(n_samples, list_dict_interventions[0]))))
    
    lmbda = 0.2
    problem = solver.solve_problem(lmbda, list_environments, solver.generate_intervention(n_samples,{}))
    print('Estimator with lmbda set to {}: \n{}'.format(lmbda, (problem.variables()[0].value)))
    
    problem_2 = solver.solve_problem_CV(list_environments, solver.generate_intervention(n_samples,{}))
    print('Estimator with lmbda chosen by CV (selected value is {:.4f}): \n{}'.format(solver.selected_lmbda,
                                                                              (problem_2.variables()[0].value)))


Simulation for sample size = 100
True beta: 
[ 2  1 -1  0  0  0  0]
Least squares estimate of beta: 
[ 3.1246  0.8675 -1.3908 -2.2716 -0.3388 -0.3811 -0.2122]
Lasso CV estimate of beta: 
[ 2.0963  0.9511 -2.2289  0.4411  2.1925 -1.4421  0.2773]
Estimator with lmbda set to 0.2: 
[ 2.1945  0.5978 -0.8936  0.2569  0.      0.1242  0.2977]
Estimator with lmbda chosen by CV (selected value is 0.1585): 
[ 1.9758  0.3378 -1.0316  0.0537 -0.     -0.0778 -0.    ]

Simulation for sample size = 500
True beta: 
[ 2  1 -1  0  0  0  0]
Least squares estimate of beta: 
[ 2.9981  0.9379 -1.4927 -1.951   0.012  -0.3164 -0.6845]
Lasso CV estimate of beta: 
[ 1.9207  0.8973 -2.4056  0.079   2.8836 -1.306  -0.2705]
Estimator with lmbda set to 0.2: 
[ 1.9548  0.9378 -1.0542 -0.0354 -0.     -0.2096  0.    ]
Estimator with lmbda chosen by CV (selected value is 0.2512): 
[ 1.8892  1.2124 -0.9115 -0.     -0.     -0.     -0.    ]

Simulation for sample size = 1000
True beta: 
[ 2  1 -1  0  0  0  0]
Least square

In [ ]:
for n_samples in np.array([100,500,1000,10000,100000,500000,1000000]):
    print('\nSimulation for sample size = {}'.format(n_samples))
    list_dict_interventions = [{i:{'type':'independent'} for i in np.array([1,4])}]
    solver = SolveProblem(connectivity_e0,x_indices,y_index)
    list_environments = [solver.generate_intervention(n_samples, dict_interventions)
                         for dict_interventions in list_dict_interventions]
    
    print('True beta: \n{}'.format(solver.beta))
    print('Least squares estimate of beta: \n{}'.format(solver.estimator_LR(solver.generate_intervention(n_samples, {}))))
    print('Lasso CV estimate of beta: \n{}'.format(solver.estimator_Lasso(solver.generate_intervention(n_samples, list_dict_interventions[0]))))
    
    lmbda = 0.2
    problem = solver.solve_problem(lmbda, list_environments, solver.generate_intervention(n_samples,{}))
    print('Estimator with lmbda set to {}: \n{}'.format(lmbda, (problem.variables()[0].value)))
    
    problem_2 = solver.solve_problem_CV(list_environments, solver.generate_intervention(n_samples,{}))
    print('Estimator with lmbda chosen by CV (selected value is {:.4f}): \n{}'.format(solver.selected_lmbda,
                                                                              (problem_2.variables()[0].value)))